# Generated by Django 4.2.3 on 2023-07-31 11:31

import ExamProject.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[ExamProject.accounts.models.only_letters, django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='profile_picture',
            field=models.URLField(blank=True, default='/static/images/person.png'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='username',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
