# Generated by Django 4.2.3 on 2023-08-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_storeuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
