# Generated by Django 4.2.3 on 2023-08-05 09:43

import ExamProject.accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_storeuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[ExamProject.accounts.models.only_nums, django.core.validators.MinLengthValidator(10)]),
        ),
    ]
