# Generated by Django 4.2.3 on 2023-08-08 11:56

import ExamProject.common.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[ExamProject.common.models.only_letters, django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=30, validators=[ExamProject.common.models.only_letters, django.core.validators.MinLengthValidator(2)])),
                ('profile_photo', models.ImageField(blank=True, upload_to='team_members/')),
                ('description', models.TextField(max_length=35)),
                ('twitter_socials', models.URLField()),
                ('facebook_socials', models.URLField()),
                ('instagram_socials', models.URLField()),
            ],
        ),
    ]
