# Generated by Django 4.2.3 on 2023-08-10 18:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('brand', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('type', models.CharField(choices=[('Supplements', 'Supplements'), ('Equipment', 'Equipment')], default='Supplements', max_length=50)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='products/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
