# Generated by Django 4.2.3 on 2023-08-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productcategory_remove_product_type_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
